# This is a basic workflow to help you get started with Actions
# Based on https://www.zonca.dev/posts/2024-04-17-overleaf-github-action
name: Overleaf Force push

# Controls when the workflow will run
on:
  # On push on main branch and on overleaf files
  push:
    branches:
      - main
    paths:
      - root/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync-overleaf:
    name: Synchronize with Overleaf
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_TOKEN }}
        fetch-depth: 0
    - name: Configure Overleaf remote
      run: git remote add overleaf https://git:${{ secrets.OVERLEAF_TOKEN }}@git.overleaf.com/${{ secrets.OVERLEAF_PROJECT_ID }}
    - name: Setup git name
      run: git config --global user.name "Samulix20"
    - name: Setup git email
      run: git config --global user.email ${{ secrets.USER_EMAIL }}
    - name: Push changes to Overleaf
      run: git push overleaf HEAD:master
